name: Build

# Capture push events with the tag v* eg. v1.0 etc.
on:
    push:
        tags:
            - '*'

jobs:

  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    permissions: write-all
    steps:
    - name: Create Release # Create a new release on Github
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Output Release URL File # Get the release url
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt

    - name: Save Release URL File for publish # Save the url for future use
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  build: # Build the application and add it to the releases
    name: Build packages
    needs: createrelease
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy: # Run the same steps on two different os
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -n bterm ./src/main.py &&
                cd src/dist/ &&
                zip -r9 bterm bterm.app/                
            OUT_FILE_NAME: bterm.zip
            ASSET_MIME: application/zip

          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -n bterm ./src/main.py
            OUT_FILE_NAME: bterm.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable

    steps:
    # Setup enviroment
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    # Build
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}

    # Upload
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v1
      with:
        name: release_url
    
    - name: Get Release File Name & Upload URL
      id: get_release_info
      shell: bash
      run: |
        value=`cat release_url/release_url.txt`
        echo ::set-output name=upload_url::$value    

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./dist/${{ matrix.OUT_FILE_NAME}}
        asset_name: ${{ matrix.OUT_FILE_NAME}}
        asset_content_type: ${{ matrix.ASSET_MIME}}

